testActivities2 = [
    {"id": "X", "duration": 3, "predecessor": []},
    {"id": "A", "duration": 5, "predecessor": ["X"]},
    {"id": "B", "duration": 3, "predecessor": ["X"]},
    {"id": "C", "duration": 7, "predecessor": ["B", "A"]},
]

testResults2 = [
    {
        "critical": True,
        "duration": 3,
        "ef": 3,
        "es": 0,
        "ff": 0,
        "id": "X",
        "lf": 3,
        "ls": 0,
        "predecessor": [],
        "successor": ["B", "A"],
        "tf": 0,
    },
    {
        "critical": True,
        "duration": 5,
        "ef": 8,
        "es": 3,
        "ff": 0,
        "id": "A",
        "lf": 8,
        "ls": 3,
        "predecessor": ["X"],
        "successor": ["C"],
        "tf": 0,
    },
    {
        "critical": False,
        "duration": 3,
        "ef": 6,
        "es": 3,
        "ff": 2,
        "id": "B",
        "lf": 8,
        "ls": 5,
        "predecessor": ["X"],
        "successor": ["C"],
        "tf": 2,
    },
    {
        "critical": True,
        "duration": 7,
        "ef": 15,
        "es": 8,
        "ff": 0,
        "id": "C",
        "lf": 15,
        "ls": 8,
        "predecessor": ["B", "A"],
        "successor": [],
        "tf": 0,
    },
]