testActivities1 = [
    {"id": "A", "duration": 3, "predecessor": []},
    {"id": "B", "duration": 3, "predecessor": []},
    {"id": "C", "duration": 3, "predecessor": ["A", "B"]},
    {"id": "D", "duration": 4, "predecessor": ["A", "B"]},
    {"id": "E", "duration": 3, "predecessor": ["C"]},
    {"id": "F", "duration": 6, "predecessor": ["C"]},
    {"id": "G", "duration": 2, "predecessor": ["D", "E"]},
    {"id": "H", "duration": 5, "predecessor": ["F", "G"]},
]

testActivities1_1 = [
    {
        "id": "A",
        "duration": 2.79,
        "min_duration": 1,
        "ml_duration": 2,
        "max_duration": 4,
        "predecessor": [],
    },
    {
        "id": "B",
        "duration": 3.19,
        "min_duration": 2.5,
        "ml_duration": 3,
        "max_duration": 3.5,
        "predecessor": [],
    },
    {
        "id": "C",
        "duration": 2.30,
        "min_duration": 2,
        "ml_duration": 3,
        "max_duration": 4,
        "predecessor": ["A", "B"],
    },
    {
        "id": "D",
        "duration": 3.82,
        "min_duration": 3.5,
        "ml_duration": 4,
        "max_duration": 4.5,
        "predecessor": ["A", "B"],
    },
    {
        "id": "E",
        "duration": 3.86,
        "min_duration": 2,
        "ml_duration": None,
        "max_duration": 4,
        "predecessor": ["C"],
    },
    {
        "id": "F",
        "duration": 5.53,
        "min_duration": 5,
        "ml_duration": None,
        "max_duration": 7,
        "predecessor": ["C"],
    },
    {
        "id": "G",
        "duration": 4.60,
        "min_duration": 1,
        "ml_duration": None,
        "max_duration": 5,
        "predecessor": ["D", "E"],
    },
    {
        "id": "H",
        "duration": 4.27,
        "min_duration": 4,
        "ml_duration": None,
        "max_duration": 7,
        "predecessor": ["F", "G"],
    },
]

testActivities2 = [
    {"id": "X", "duration": 3, "predecessor": []},
    {"id": "A", "duration": 5, "predecessor": ["X"]},
    {"id": "B", "duration": 3, "predecessor": ["X"]},
    {"id": "C", "duration": 7, "predecessor": ["B", "A"]},
]

testActivities3 = [
    {"id": "A", "duration": 6, "predecessor": []},
    {"id": "B", "duration": 5, "predecessor": []},
    {"id": "C", "duration": 10, "predecessor": ["A"]},
    {"id": "D", "duration": 3, "predecessor": ["A", "B"]},
    {"id": "E", "duration": 7, "predecessor": ["D"]},
    {"id": "F", "duration": 3, "predecessor": ["C", "E"]},
    {"id": "G", "duration": 4, "predecessor": ["C", "E"]},
    {"id": "H", "duration": 5, "predecessor": ["C", "E"]},
    {"id": "I", "duration": 6, "predecessor": ["F"]},
    {"id": "J", "duration": 3, "predecessor": ["H"]},
    {"id": "K", "duration": 2, "predecessor": ["I", "G", "J"]},
]

testResults1 = [
    {
        "id": "A",
        "duration": 3,
        "predecessor": [],
        "es": 0,
        "ef": 3,
        "ls": 0,
        "lf": 3,
        "successor": ["C", "D"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "B",
        "duration": 3,
        "predecessor": [],
        "es": 0,
        "ef": 3,
        "ls": 0,
        "lf": 3,
        "successor": ["C", "D"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "C",
        "duration": 3,
        "predecessor": ["A", "B"],
        "es": 3,
        "ef": 6,
        "ls": 3,
        "lf": 6,
        "successor": ["F", "E"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "D",
        "duration": 4,
        "predecessor": ["A", "B"],
        "es": 3,
        "ef": 7,
        "ls": 6,
        "lf": 10,
        "successor": ["G"],
        "tf": 3,
        "ff": 2,
        "critical": False,
    },
    {
        "id": "E",
        "duration": 3,
        "predecessor": ["C"],
        "es": 6,
        "ef": 9,
        "ls": 7,
        "lf": 10,
        "successor": ["G"],
        "tf": 1,
        "ff": 0,
        "critical": False,
    },
    {
        "id": "G",
        "duration": 2,
        "predecessor": ["D", "E"],
        "es": 9,
        "ef": 11,
        "ls": 10,
        "lf": 12,
        "successor": ["H"],
        "tf": 1,
        "ff": 1,
        "critical": False,
    },
    {
        "id": "F",
        "duration": 6,
        "predecessor": ["C"],
        "es": 6,
        "ef": 12,
        "ls": 6,
        "lf": 12,
        "successor": ["H"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "H",
        "duration": 5,
        "predecessor": ["F", "G"],
        "es": 12,
        "ef": 17,
        "ls": 12,
        "lf": 17,
        "successor": [],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
]

testResults1_1 = [
    {
        "critical": False,
        "duration": 2.79,
        "ef": 2.79,
        "es": 0,
        "ff": 0.4,
        "id": "A",
        "lf": 3.19,
        "ls": 0.4,
        "max_duration": 4,
        "min_duration": 1,
        "ml_duration": 2,
        "predecessor": [],
        "successor": ["C", "D"],
        "tf": 0.4,
    },
    {
        "critical": False,
        "duration": 3.19,
        "ef": 3.19,
        "es": 0,
        "ff": 0.0,
        "id": "B",
        "lf": 3.19,
        "ls": 0.0,
        "max_duration": 3.5,
        "min_duration": 2.5,
        "ml_duration": 3,
        "predecessor": [],
        "successor": ["C", "D"],
        "tf": 0.0,
    },
    {
        "critical": True,
        "duration": 2.3,
        "ef": 5.49,
        "es": 3.19,
        "ff": 0.0,
        "id": "C",
        "lf": 5.49,
        "ls": 3.19,
        "max_duration": 4,
        "min_duration": 2,
        "ml_duration": 3,
        "predecessor": ["A", "B"],
        "successor": ["F", "E"],
        "tf": 0.0,
    },
    {
        "critical": False,
        "duration": 3.82,
        "ef": 7.01,
        "es": 3.19,
        "ff": 2.34,
        "id": "D",
        "lf": 9.35,
        "ls": 5.53,
        "max_duration": 4.5,
        "min_duration": 3.5,
        "ml_duration": 4,
        "predecessor": ["A", "B"],
        "successor": ["G"],
        "tf": 2.34,
    },
    {
        "critical": True,
        "duration": 3.86,
        "ef": 9.35,
        "es": 5.49,
        "ff": 0.0,
        "id": "E",
        "lf": 9.35,
        "ls": 5.49,
        "max_duration": 4,
        "min_duration": 2,
        "ml_duration": None,
        "predecessor": ["C"],
        "successor": ["G"],
        "tf": 0.0,
    },
    {
        "critical": False,
        "duration": 5.53,
        "ef": 11.02,
        "es": 5.49,
        "ff": 2.93,
        "id": "F",
        "lf": 13.95,
        "ls": 8.42,
        "max_duration": 7,
        "min_duration": 5,
        "ml_duration": None,
        "predecessor": ["C"],
        "successor": ["H"],
        "tf": 2.93,
    },
    {
        "critical": True,
        "duration": 4.6,
        "ef": 13.95,
        "es": 9.35,
        "ff": 0.0,
        "id": "G",
        "lf": 13.95,
        "ls": 9.35,
        "max_duration": 5,
        "min_duration": 1,
        "ml_duration": None,
        "predecessor": ["D", "E"],
        "successor": ["H"],
        "tf": 0.0,
    },
    {
        "critical": True,
        "duration": 4.27,
        "ef": 18.22,
        "es": 13.95,
        "ff": 0.0,
        "id": "H",
        "lf": 18.22,
        "ls": 13.95,
        "max_duration": 7,
        "min_duration": 4,
        "ml_duration": None,
        "predecessor": ["F", "G"],
        "successor": [],
        "tf": 0.0,
    },
]

testResults2 = [
    {
        "critical": True,
        "duration": 3,
        "ef": 3,
        "es": 0,
        "ff": 0,
        "id": "X",
        "lf": 3,
        "ls": 0,
        "predecessor": [],
        "successor": ["B", "A"],
        "tf": 0,
    },
    {
        "critical": True,
        "duration": 5,
        "ef": 8,
        "es": 3,
        "ff": 0,
        "id": "A",
        "lf": 8,
        "ls": 3,
        "predecessor": ["X"],
        "successor": ["C"],
        "tf": 0,
    },
    {
        "critical": False,
        "duration": 3,
        "ef": 6,
        "es": 3,
        "ff": 2,
        "id": "B",
        "lf": 8,
        "ls": 5,
        "predecessor": ["X"],
        "successor": ["C"],
        "tf": 2,
    },
    {
        "critical": True,
        "duration": 7,
        "ef": 15,
        "es": 8,
        "ff": 0,
        "id": "C",
        "lf": 15,
        "ls": 8,
        "predecessor": ["B", "A"],
        "successor": [],
        "tf": 0,
    },
]

testResults3 = [
    {
        "id": "B",
        "duration": 5,
        "predecessor": [],
        "es": 0,
        "ef": 5,
        "ls": 1,
        "lf": 6,
        "successor": ["D"],
        "tf": 1,
        "ff": 1,
        "critical": False,
    },
    {
        "id": "A",
        "duration": 6,
        "predecessor": [],
        "es": 0,
        "ef": 6,
        "ls": 0,
        "lf": 6,
        "successor": ["C", "D"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "D",
        "duration": 3,
        "predecessor": ["A", "B"],
        "es": 6,
        "ef": 9,
        "ls": 6,
        "lf": 9,
        "successor": ["E"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "C",
        "duration": 10,
        "predecessor": ["A"],
        "es": 6,
        "ef": 16,
        "ls": 6,
        "lf": 16,
        "successor": ["F", "G", "H"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "E",
        "duration": 7,
        "predecessor": ["D"],
        "es": 9,
        "ef": 16,
        "ls": 9,
        "lf": 16,
        "successor": ["F", "G", "H"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "F",
        "duration": 3,
        "predecessor": ["C", "E"],
        "es": 16,
        "ef": 19,
        "ls": 16,
        "lf": 19,
        "successor": ["I"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "H",
        "duration": 5,
        "predecessor": ["C", "E"],
        "es": 16,
        "ef": 21,
        "ls": 17,
        "lf": 22,
        "successor": ["J"],
        "tf": 1,
        "ff": 0,
        "critical": False,
    },
    {
        "id": "G",
        "duration": 4,
        "predecessor": ["C", "E"],
        "es": 16,
        "ef": 20,
        "ls": 21,
        "lf": 25,
        "successor": ["K"],
        "tf": 5,
        "ff": 5,
        "critical": False,
    },
    {
        "id": "J",
        "duration": 3,
        "predecessor": ["H"],
        "es": 21,
        "ef": 24,
        "ls": 22,
        "lf": 25,
        "successor": ["K"],
        "tf": 1,
        "ff": 1,
        "critical": False,
    },
    {
        "id": "I",
        "duration": 6,
        "predecessor": ["F"],
        "es": 19,
        "ef": 25,
        "ls": 19,
        "lf": 25,
        "successor": ["K"],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
    {
        "id": "K",
        "duration": 2,
        "predecessor": ["I", "G", "J"],
        "es": 25,
        "ef": 27,
        "ls": 25,
        "lf": 27,
        "successor": [],
        "tf": 0,
        "ff": 0,
        "critical": True,
    },
]
